const serviceApi = [
  {
    id: 1,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    reviews: ["bi-star-fill", "bi-star-fill", "bi-star-fill"],
    price: 80,
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 2,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    reviews: ["bi-star-fill", "bi-star-fill", "bi-star-fill"],
    price: 80,
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 3,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill", "bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 4,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill", "bi-star-fill", "bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 5,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 6,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill", "bi-star-fill", "bi-star-fill", "bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 7,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: [" bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 8,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill", "bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 9,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill", "bi-star-fill", "bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 10,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 11,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: ["bi-star-fill", "bi-star-fill"],
    add: "btn btn-outline-dark mt-auto",
  },
  {
    id: 12,
    img: "https://dummyimage.com/450x300/dee2e6/6c757d.jpg",
    name: "Special Item",
    price: 80,
    reviews: [
      "bi-star-fill",
      "bi-star-fill",
      "bi-star-fill",
      "bi-star-fill",
      "bi-star-fill",
    ],
    add: "btn btn-outline-dark mt-auto",
  },
];

module.exports = serviceApi;
